apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-auto-deployment
  namespace: default
  labels:
    app: sealed-auto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sealed-auto
  template:
    metadata:
      labels:
        app: sealed-auto
    spec:
      containers:
        - name: sealed-auto
          image: sealedautoacr.azurecr.io/sealed-auto:v1
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      imagePullSecrets:
        - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: sealed-auto-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: sealed-auto
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
